### PR TITLE
Delete memberships app from the project (#149)

### LINKED ISSUE #149: Remove Memberships App

### PR DESCRIPTION
**Pull request by itshesam**
closes #149 

I checked usages of the model, there weren't any, so i just deleted the app and removed the app name from settings. i searched a bit to ensure that there will be no migration needed to remove a model, so the only remaining thing is to drop the table in database.

### CODE REVIEW

**Comment by itshesam** [comment]
so is it like a 2-step deletion ? at first we apply the delete migration without actually deleting the app to drop the table and then we can remove the directory and app itself. is it correct ?

**Comment by itshesam** [comment]
@danielzeljko 
can you give me a feedback on this ?

**Comment by danielzeljko** [comment]
Yes -- it's a two step process. I'll look into this PR sometime next week as I'm currently on vacation until the 22th.

**Comment by itshesam** [comment]
@danielzeljko 

Is there anything else that needs to be addressed ? I think it can be merged if you're ready

**Pull request merged**
