### PR TITLE
Fix translation bug in notifications (#191)

### LINKED ISSUE #191: Notifications appear in wrong language despite site language settings
I have my site language set to English, but I'm receiving notifications in Japanese. My initial assumption is that the notifications are appearing in the language setting of the sender, rather than adhering to my own site language settings.

image

### PR DESCRIPTION
**Pull request by itshesam**
closes #191 

For all of these notification types, we should add translation. I considered it another task. This will fix the current bug and if we correct the translation files it will be fine.

### CODE REVIEW

**Comment by danielzeljko** [comment]
Thank you for working on this.

Your fix just makes these strings untranslatable and all of the notifications will default to English. Can you clarify exactly what you had in mind?

**Comment by itshesam** [comment]
@danielzeljko 
we are using ```notify.send``` whenever something happens like a correction and we call this on the side of the user that is correcting the text, so when we have:
```python
notify.send(
    sender=current_user,
    recipient=post.user,
    verb=_("corrected"),
    action_object=post,
    notification_type="new_correction",
)
```
the ```verb``` will be in the language of the person that is causing the notification(the person that is correcting) and when the notification is read by the other person, the verb is in the language of the corrector person, Therefore we need to keep all verbs in English and then they will be translated later in the templates.

**Comment by danielzeljko** [comment]
> Therefore we need to keep all verbs in English and then they will be translated later in the templates.

If you're thinking about adding these strings directly in the notification templates, then I would leave out the `verb` as it's a bit redundant (if it's an optional param).

For example,

```
notify.send(
    sender=current_user,
    recipient=post.user,
    action_object=post,
    notification_type="new_correction",
)
```

```
{% if notification.notification_type == "new_correction" %}
  {% blocktranslate with username=... post=... %}
     {username} corrected {post}
  //...
//...
```

I think this approach would be the cleanest. Nice idea.

**Comment by itshesam** [comment]
It seems that ```verb``` is a required argument, can't skip it. I think the ```verb``` was supposed to show the notification type but it's a little bit misleading name for the purpose.

**Comment by danielzeljko** [comment]
In that case, we can just keep the verb as it is. Let's include the template changes with this PR.

**Comment by danielzeljko** [comment]
I'm just checking in to see if you have any blockers or need help. I'd love to get this merged in by Wed. Oct 18th.

**Comment by itshesam** [comment]
It's ready to be merged actually. There is no changes needed in templates. The verb is getting translated in templates.

**Comment by danielzeljko** [comment]
Thank you for the speedy response and letting me know that you believe the code is ready to be merged. However, I'd like to clarify my understanding of how translations work in Django to ensure we're on the same page.

When `translate()` is removed from `notify.send`, the string is no longer marked for translation. This means that when we run `makemessages`, this string won't be included in the `.po` file. If you subsequently run `compilemessages`, any previous translation for that string will be lost.

The template tag `{% translate notification.verb %}` will attempt to translate `notification.verb` when the template is rendered. However, since the string is not in the `.po` files, the translation will not be found. As a result, the original English string will be displayed for international users which isn't ideal.

So, while the `verb` is getting translated in the template, removing `translate()` from `notify.send` would mean that the necessary `.po` entries for that translation would eventually be lost, unless marked elsewhere. So, I believe that some changes are still needed in the templates to ensure that the translation works as expected.

**Comment by itshesam** [comment]
You said it all right. The catch is if we add translations for our "verbs" manually, the future ```makemessages``` will not remove them even if they are not present in the source code unless we use ```--no-obsolete``` option.

**Comment by itshesam** [comment]
@danielzeljko 
Please give me some feedback on this and #181  :))))

**Review by danielzeljko — DISMISSED** [review]
Removing the translate tags from notify is good. Let's keep that how it is. The only thing left is to implement the changes as we have previous discussed which is to add the translations directly in the templates based on the `notification_type`.

As for 181, I have already provided an update informing you that I won't be able to get to it until I come back from my trip. So we'll have to wait until then!

**Comment by itshesam** [comment]
@danielzeljko sorry, i was busy for a few days.

translation is going to happen already with ```{% translate notification.verb %}```, no need to add anything. We just need to add translation to our notification types in our ```po``` files

**Comment by danielzeljko** [comment]
Thank you for the clarification, and I appreciate your patience in this discussion 🙌 

To recap our conversation, when you pull from the main branch, you'll receive the updated translation files. If you run `makemessages` without the `no-obsolete` flag, the previously translated verbs will be marked as obsolete (`#~`). For example:

```
#~ msgid "followed you"
#~ msgstr "あなたをフォローしました"
```

Please correct me if I am wrong, but what your approach would be is to manually delete obsolete markings (`#~`) from the strings from the `.po` files to mark them as active. For example:

```
msgid "followed you"
msgstr "あなたをフォローしました"
```

Now the key question is: if we were to run make or compile messages again, would these strings be marked as obsolete once more? For example:

```
#~ msgid "followed you"
#~ msgstr "あなたをフォローしました"
```

If these strings are remarked as obsolete, I'm afraid it will create ongoing maintenance concerns. I also wouldn't like to have too many obsolete strings in the project, so eventually I'd love to run those commands with the `no-obsolete` flag. I'd love to hear your thoughts!

If these strings will not be remarked as obsolete, then I think we are ready to proceed with the next steps:

- [ ] pull from the latest branch
- [ ] remove the obsolete markings
- [ ] add any missing translations using ChatGPT or DeepL

**Comment by itshesam** [comment]
@danielzeljko 

I think you got the ```no-obsolete``` option wrong. If we run ```makemessages --no-obsolete``` all words that are not in the code base get removed, but if we just run ```makemssages``` no message is getting deleted, it just adds new ones. So we can manually add translations for our "verbs" and don't worry about the rest because i assume that we don't ever use ```no-obsolete``` option.

If we don't want to this, we can hard-code our ```verbs``` into some ```__init__.py``` like:
```python3
EXTRA_WORDS = [
    _("corrected"),
    _("followed you"),
]
```
This will make sure that our verbs are going to get collected with ```makemessages``` command

**Comment by danielzeljko** [comment]
Thanks for clarifying and teaching me something new @itshesam!

In that case, I think it would be better to just hard-code those translations elsewhere. I would have been onboard adding them inside of an `__init__.py` if we had a notifications app, but I think we can add it to either the base settings or perhaps create a new file in the root app directory called `custom_translations.py` or something like that. I'm a little iffy about adding it to the base settings since we're breaking separation of concerns. I'm open to discussion!

**Comment by itshesam** [comment]
@danielzeljko 

Think that i finally found it :))) There is ```gettext_noop``` that exactly does what we want. We only need to run ```makemessages```. I ran it but there were some changes related to previous changes you made so i left it for you to resolve them, you can run the command and push your commit on this branch

**Comment by danielzeljko** [comment]
I've resolved them, but it seems `gh pr checkout 194` creates a new branch in origin. I was not able to push them here.

New PR is located at #257

**Pull request merged**
